-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.ContainerDetails exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
id : SelectionSet Gql.DockerAPI.ScalarCodecs.Id Gql.DockerAPI.Object.ContainerDetails
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
created : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Date) Gql.DockerAPI.Object.ContainerDetails
created =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "created" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
path : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
path =
    Object.selectionForField "(Maybe String)" "path" [] (Decode.string |> Decode.nullable)


{-| -}
args : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.ContainerDetails
args =
    Object.selectionForField "(Maybe (List (Maybe String)))" "args" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
config : SelectionSet decodesTo Gql.DockerAPI.Object.ContainerConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ContainerDetails
config object_ =
    Object.selectionForCompositeField "config" [] object_ (identity >> Decode.nullable)


{-| -}
hostConfig : SelectionSet decodesTo Gql.DockerAPI.Object.HostConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ContainerDetails
hostConfig object_ =
    Object.selectionForCompositeField "hostConfig" [] object_ (identity >> Decode.nullable)


{-| -}
state : SelectionSet decodesTo Gql.DockerAPI.Object.ContainerState -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ContainerDetails
state object_ =
    Object.selectionForCompositeField "state" [] object_ (identity >> Decode.nullable)


{-| -}
image : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
image =
    Object.selectionForField "(Maybe String)" "image" [] (Decode.string |> Decode.nullable)


{-| -}
networkSettings : SelectionSet decodesTo Gql.DockerAPI.Object.NetworkSettings -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ContainerDetails
networkSettings object_ =
    Object.selectionForCompositeField "networkSettings" [] object_ (identity >> Decode.nullable)


{-| -}
resolvConfPath : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
resolvConfPath =
    Object.selectionForField "(Maybe String)" "resolvConfPath" [] (Decode.string |> Decode.nullable)


{-| -}
hostnamePath : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
hostnamePath =
    Object.selectionForField "(Maybe String)" "hostnamePath" [] (Decode.string |> Decode.nullable)


{-| -}
hostsPath : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
hostsPath =
    Object.selectionForField "(Maybe String)" "hostsPath" [] (Decode.string |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
driver : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
driver =
    Object.selectionForField "(Maybe String)" "driver" [] (Decode.string |> Decode.nullable)


{-| -}
execDriver : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
execDriver =
    Object.selectionForField "(Maybe String)" "execDriver" [] (Decode.string |> Decode.nullable)


{-| -}
processLabel : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
processLabel =
    Object.selectionForField "(Maybe String)" "processLabel" [] (Decode.string |> Decode.nullable)


{-| -}
mountLabel : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
mountLabel =
    Object.selectionForField "(Maybe String)" "mountLabel" [] (Decode.string |> Decode.nullable)


{-| -}
volumes : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.ContainerDetails
volumes =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "volumes" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
volumesRw : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.ContainerDetails
volumesRw =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "volumesRw" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
appArmorProfile : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
appArmorProfile =
    Object.selectionForField "(Maybe String)" "appArmorProfile" [] (Decode.string |> Decode.nullable)


{-| -}
execIds : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.ContainerDetails
execIds =
    Object.selectionForField "(Maybe (List (Maybe String)))" "execIds" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
logPath : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerDetails
logPath =
    Object.selectionForField "(Maybe String)" "logPath" [] (Decode.string |> Decode.nullable)


{-| -}
restartCount : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.ContainerDetails
restartCount =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "restartCount" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
mounts : SelectionSet decodesTo Gql.DockerAPI.Object.ContainerMount -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.ContainerDetails
mounts object_ =
    Object.selectionForCompositeField "mounts" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
node : SelectionSet decodesTo Gql.DockerAPI.Object.Node -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ContainerDetails
node object_ =
    Object.selectionForCompositeField "node" [] object_ (identity >> Decode.nullable)
