-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.ContainerMount exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
type_ : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerMount
type_ =
    Object.selectionForField "(Maybe String)" "type" [] (Decode.string |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerMount
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
source : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerMount
source =
    Object.selectionForField "(Maybe String)" "source" [] (Decode.string |> Decode.nullable)


{-| -}
destination : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerMount
destination =
    Object.selectionForField "(Maybe String)" "destination" [] (Decode.string |> Decode.nullable)


{-| -}
driver : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerMount
driver =
    Object.selectionForField "(Maybe String)" "driver" [] (Decode.string |> Decode.nullable)


{-| -}
mode : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerMount
mode =
    Object.selectionForField "(Maybe String)" "mode" [] (Decode.string |> Decode.nullable)


{-| -}
rw : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.ContainerMount
rw =
    Object.selectionForField "(Maybe Bool)" "rw" [] (Decode.bool |> Decode.nullable)


{-| -}
propagation : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerMount
propagation =
    Object.selectionForField "(Maybe String)" "propagation" [] (Decode.string |> Decode.nullable)
