-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.ContainerConfig exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
hostname : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerConfig
hostname =
    Object.selectionForField "(Maybe String)" "hostname" [] (Decode.string |> Decode.nullable)


{-| -}
domainname : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerConfig
domainname =
    Object.selectionForField "(Maybe String)" "domainname" [] (Decode.string |> Decode.nullable)


{-| -}
user : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerConfig
user =
    Object.selectionForField "(Maybe String)" "user" [] (Decode.string |> Decode.nullable)


{-| -}
attachStdin : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.ContainerConfig
attachStdin =
    Object.selectionForField "(Maybe Bool)" "attachStdin" [] (Decode.bool |> Decode.nullable)


{-| -}
attachStdout : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.ContainerConfig
attachStdout =
    Object.selectionForField "(Maybe Bool)" "attachStdout" [] (Decode.bool |> Decode.nullable)


{-| -}
attachStderr : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.ContainerConfig
attachStderr =
    Object.selectionForField "(Maybe Bool)" "attachStderr" [] (Decode.bool |> Decode.nullable)


{-| -}
portSpecs : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.ContainerConfig
portSpecs =
    Object.selectionForField "(Maybe (List (Maybe String)))" "portSpecs" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
exposedPorts : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringSet) Gql.DockerAPI.Object.ContainerConfig
exposedPorts =
    Object.selectionForField "(Maybe ScalarCodecs.StringSet)" "exposedPorts" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringSet |> .decoder |> Decode.nullable)


{-| -}
tty : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.ContainerConfig
tty =
    Object.selectionForField "(Maybe Bool)" "tty" [] (Decode.bool |> Decode.nullable)


{-| -}
openStdin : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.ContainerConfig
openStdin =
    Object.selectionForField "(Maybe Bool)" "openStdin" [] (Decode.bool |> Decode.nullable)


{-| -}
stdinOnce : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.ContainerConfig
stdinOnce =
    Object.selectionForField "(Maybe Bool)" "stdinOnce" [] (Decode.bool |> Decode.nullable)


{-| -}
env : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.ContainerConfig
env =
    Object.selectionForField "(Maybe (List (Maybe String)))" "env" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
cmd : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.ContainerConfig
cmd =
    Object.selectionForField "(Maybe (List (Maybe String)))" "cmd" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
image : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerConfig
image =
    Object.selectionForField "(Maybe String)" "image" [] (Decode.string |> Decode.nullable)


{-| -}
volumeNames : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringSet) Gql.DockerAPI.Object.ContainerConfig
volumeNames =
    Object.selectionForField "(Maybe ScalarCodecs.StringSet)" "volumeNames" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringSet |> .decoder |> Decode.nullable)


{-| -}
volumes : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.ContainerConfig
volumes =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "volumes" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
workingDir : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerConfig
workingDir =
    Object.selectionForField "(Maybe String)" "workingDir" [] (Decode.string |> Decode.nullable)


{-| -}
entrypoint : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.ContainerConfig
entrypoint =
    Object.selectionForField "(Maybe (List (Maybe String)))" "entrypoint" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
networkDisabled : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.ContainerConfig
networkDisabled =
    Object.selectionForField "(Maybe Bool)" "networkDisabled" [] (Decode.bool |> Decode.nullable)


{-| -}
onBuild : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.ContainerConfig
onBuild =
    Object.selectionForField "(Maybe (List (Maybe String)))" "onBuild" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
labels : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.ContainerConfig
labels =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "labels" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
macAddress : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerConfig
macAddress =
    Object.selectionForField "(Maybe String)" "macAddress" [] (Decode.string |> Decode.nullable)


{-| -}
hostConfig : SelectionSet decodesTo Gql.DockerAPI.Object.HostConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ContainerConfig
hostConfig object_ =
    Object.selectionForCompositeField "hostConfig" [] object_ (identity >> Decode.nullable)


{-| -}
stopSignal : SelectionSet (Maybe String) Gql.DockerAPI.Object.ContainerConfig
stopSignal =
    Object.selectionForField "(Maybe String)" "stopSignal" [] (Decode.string |> Decode.nullable)


{-| -}
healthcheck : SelectionSet decodesTo Gql.DockerAPI.Object.Healthcheck -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ContainerConfig
healthcheck object_ =
    Object.selectionForCompositeField "healthcheck" [] object_ (identity >> Decode.nullable)


{-| -}
networkingConfig : SelectionSet decodesTo Gql.DockerAPI.Object.NetworkingConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ContainerConfig
networkingConfig object_ =
    Object.selectionForCompositeField "networkingConfig" [] object_ (identity >> Decode.nullable)
