-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.Healthcheck exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
test : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.Healthcheck
test =
    Object.selectionForField "(Maybe (List (Maybe String)))" "test" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
interval : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.Healthcheck
interval =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "interval" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
timeout : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.Healthcheck
timeout =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "timeout" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
retries : SelectionSet (Maybe Int) Gql.DockerAPI.Object.Healthcheck
retries =
    Object.selectionForField "(Maybe Int)" "retries" [] (Decode.int |> Decode.nullable)


{-| -}
startPeriod : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.Healthcheck
startPeriod =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "startPeriod" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)
