-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.HostConfig exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
binds : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
binds =
    Object.selectionForField "(Maybe (List (Maybe String)))" "binds" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
blkioWeight : SelectionSet (Maybe Int) Gql.DockerAPI.Object.HostConfig
blkioWeight =
    Object.selectionForField "(Maybe Int)" "blkioWeight" [] (Decode.int |> Decode.nullable)


{-| -}
blkioWeightDevice : SelectionSet decodesTo Gql.DockerAPI.Object.BlkioWeightDevice -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.HostConfig
blkioWeightDevice object_ =
    Object.selectionForCompositeField "blkioWeightDevice" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
blkioDeviceReadBps : SelectionSet decodesTo Gql.DockerAPI.Object.BlkioDeviceRate -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.HostConfig
blkioDeviceReadBps object_ =
    Object.selectionForCompositeField "blkioDeviceReadBps" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
blkioDeviceWriteBps : SelectionSet decodesTo Gql.DockerAPI.Object.BlkioDeviceRate -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.HostConfig
blkioDeviceWriteBps object_ =
    Object.selectionForCompositeField "blkioDeviceWriteBps" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
blkioDeviceReadIOps : SelectionSet decodesTo Gql.DockerAPI.Object.BlkioDeviceRate -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.HostConfig
blkioDeviceReadIOps object_ =
    Object.selectionForCompositeField "blkioDeviceReadIOps" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
blkioDeviceWriteIOps : SelectionSet decodesTo Gql.DockerAPI.Object.BlkioDeviceRate -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.HostConfig
blkioDeviceWriteIOps object_ =
    Object.selectionForCompositeField "blkioDeviceWriteIOps" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
containerIdFile : SelectionSet (Maybe String) Gql.DockerAPI.Object.HostConfig
containerIdFile =
    Object.selectionForField "(Maybe String)" "containerIdFile" [] (Decode.string |> Decode.nullable)


{-| -}
lxcConf : SelectionSet decodesTo Gql.DockerAPI.Object.LxcConfParameter -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.HostConfig
lxcConf object_ =
    Object.selectionForCompositeField "lxcConf" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
privileged : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.HostConfig
privileged =
    Object.selectionForField "(Maybe Bool)" "privileged" [] (Decode.bool |> Decode.nullable)


{-| -}
portBindings : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.HostConfig
portBindings =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "portBindings" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
links : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
links =
    Object.selectionForField "(Maybe (List (Maybe String)))" "links" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
publishAllPorts : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.HostConfig
publishAllPorts =
    Object.selectionForField "(Maybe Bool)" "publishAllPorts" [] (Decode.bool |> Decode.nullable)


{-| -}
dns : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
dns =
    Object.selectionForField "(Maybe (List (Maybe String)))" "dns" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
dnsOptions : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
dnsOptions =
    Object.selectionForField "(Maybe (List (Maybe String)))" "dnsOptions" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
dnsSearch : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
dnsSearch =
    Object.selectionForField "(Maybe (List (Maybe String)))" "dnsSearch" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
extraHosts : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
extraHosts =
    Object.selectionForField "(Maybe (List (Maybe String)))" "extraHosts" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
volumesFrom : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
volumesFrom =
    Object.selectionForField "(Maybe (List (Maybe String)))" "volumesFrom" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
capAdd : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
capAdd =
    Object.selectionForField "(Maybe (List (Maybe String)))" "capAdd" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
capDrop : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
capDrop =
    Object.selectionForField "(Maybe (List (Maybe String)))" "capDrop" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
networkMode : SelectionSet (Maybe String) Gql.DockerAPI.Object.HostConfig
networkMode =
    Object.selectionForField "(Maybe String)" "networkMode" [] (Decode.string |> Decode.nullable)


{-| -}
securityOpt : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.HostConfig
securityOpt =
    Object.selectionForField "(Maybe (List (Maybe String)))" "securityOpt" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
devices : SelectionSet decodesTo Gql.DockerAPI.Object.Device -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.HostConfig
devices object_ =
    Object.selectionForCompositeField "devices" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
memory : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.HostConfig
memory =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "memory" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
memorySwap : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.HostConfig
memorySwap =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "memorySwap" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
memorySwappiness : SelectionSet (Maybe Int) Gql.DockerAPI.Object.HostConfig
memorySwappiness =
    Object.selectionForField "(Maybe Int)" "memorySwappiness" [] (Decode.int |> Decode.nullable)


{-| -}
memoryReservation : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.HostConfig
memoryReservation =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "memoryReservation" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
nanoCpus : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.HostConfig
nanoCpus =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "nanoCpus" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
cpuPeriod : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.HostConfig
cpuPeriod =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "cpuPeriod" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
cpuShares : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.HostConfig
cpuShares =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "cpuShares" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
cpusetCpus : SelectionSet (Maybe String) Gql.DockerAPI.Object.HostConfig
cpusetCpus =
    Object.selectionForField "(Maybe String)" "cpusetCpus" [] (Decode.string |> Decode.nullable)


{-| -}
cpusetMems : SelectionSet (Maybe String) Gql.DockerAPI.Object.HostConfig
cpusetMems =
    Object.selectionForField "(Maybe String)" "cpusetMems" [] (Decode.string |> Decode.nullable)


{-| -}
cpuQuota : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.HostConfig
cpuQuota =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "cpuQuota" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
cgroupParent : SelectionSet (Maybe String) Gql.DockerAPI.Object.HostConfig
cgroupParent =
    Object.selectionForField "(Maybe String)" "cgroupParent" [] (Decode.string |> Decode.nullable)


{-| -}
restartPolicy : SelectionSet decodesTo Gql.DockerAPI.Object.RestartPolicy -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.HostConfig
restartPolicy object_ =
    Object.selectionForCompositeField "restartPolicy" [] object_ (identity >> Decode.nullable)


{-| -}
logConfig : SelectionSet decodesTo Gql.DockerAPI.Object.LogConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.HostConfig
logConfig object_ =
    Object.selectionForCompositeField "logConfig" [] object_ (identity >> Decode.nullable)


{-| -}
ipcMode : SelectionSet (Maybe String) Gql.DockerAPI.Object.HostConfig
ipcMode =
    Object.selectionForField "(Maybe String)" "ipcMode" [] (Decode.string |> Decode.nullable)


{-| -}
ulimits : SelectionSet decodesTo Gql.DockerAPI.Object.Ulimit -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.HostConfig
ulimits object_ =
    Object.selectionForCompositeField "ulimits" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
pidMode : SelectionSet (Maybe String) Gql.DockerAPI.Object.HostConfig
pidMode =
    Object.selectionForField "(Maybe String)" "pidMode" [] (Decode.string |> Decode.nullable)


{-| -}
shmSize : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.HostConfig
shmSize =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "shmSize" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
oomKillDisable : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.HostConfig
oomKillDisable =
    Object.selectionForField "(Maybe Bool)" "oomKillDisable" [] (Decode.bool |> Decode.nullable)


{-| -}
oomScoreAdj : SelectionSet (Maybe Int) Gql.DockerAPI.Object.HostConfig
oomScoreAdj =
    Object.selectionForField "(Maybe Int)" "oomScoreAdj" [] (Decode.int |> Decode.nullable)


{-| -}
autoRemove : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.HostConfig
autoRemove =
    Object.selectionForField "(Maybe Bool)" "autoRemove" [] (Decode.bool |> Decode.nullable)


{-| -}
pidsLimit : SelectionSet (Maybe Int) Gql.DockerAPI.Object.HostConfig
pidsLimit =
    Object.selectionForField "(Maybe Int)" "pidsLimit" [] (Decode.int |> Decode.nullable)


{-| -}
tmpfs : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.HostConfig
tmpfs =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "tmpfs" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
readonlyRootfs : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.HostConfig
readonlyRootfs =
    Object.selectionForField "(Maybe Bool)" "readonlyRootfs" [] (Decode.bool |> Decode.nullable)


{-| -}
storageOpt : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.HostConfig
storageOpt =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "storageOpt" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)
