-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.Image exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
created : SelectionSet (Maybe String) Gql.DockerAPI.Object.Image
created =
    Object.selectionForField "(Maybe String)" "created" [] (Decode.string |> Decode.nullable)


{-| -}
id : SelectionSet Gql.DockerAPI.ScalarCodecs.Id Gql.DockerAPI.Object.Image
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
parentId : SelectionSet (Maybe String) Gql.DockerAPI.Object.Image
parentId =
    Object.selectionForField "(Maybe String)" "parentId" [] (Decode.string |> Decode.nullable)


{-| -}
repoTags : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.Image
repoTags =
    Object.selectionForField "(Maybe (List (Maybe String)))" "repoTags" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
repoDigests : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.Image
repoDigests =
    Object.selectionForField "(Maybe (List (Maybe String)))" "repoDigests" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
size : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.Image
size =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "size" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
virtualSize : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.Image
virtualSize =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "virtualSize" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
labels : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.Image
labels =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "labels" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
details : SelectionSet decodesTo Gql.DockerAPI.Object.ImageDetails -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.Image
details object_ =
    Object.selectionForCompositeField "details" [] object_ (identity >> Decode.nullable)


{-| -}
history : SelectionSet decodesTo Gql.DockerAPI.Object.ImageHistory -> SelectionSet (Maybe (List (Maybe decodesTo))) Gql.DockerAPI.Object.Image
history object_ =
    Object.selectionForCompositeField "history" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
