-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.ImageDetails exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
id : SelectionSet Gql.DockerAPI.ScalarCodecs.Id Gql.DockerAPI.Object.ImageDetails
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
parent : SelectionSet (Maybe String) Gql.DockerAPI.Object.ImageDetails
parent =
    Object.selectionForField "(Maybe String)" "parent" [] (Decode.string |> Decode.nullable)


{-| -}
comment : SelectionSet (Maybe String) Gql.DockerAPI.Object.ImageDetails
comment =
    Object.selectionForField "(Maybe String)" "comment" [] (Decode.string |> Decode.nullable)


{-| -}
created : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Date) Gql.DockerAPI.Object.ImageDetails
created =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "created" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
container : SelectionSet (Maybe String) Gql.DockerAPI.Object.ImageDetails
container =
    Object.selectionForField "(Maybe String)" "container" [] (Decode.string |> Decode.nullable)


{-| -}
containerConfig : SelectionSet decodesTo Gql.DockerAPI.Object.ContainerConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ImageDetails
containerConfig object_ =
    Object.selectionForCompositeField "containerConfig" [] object_ (identity >> Decode.nullable)


{-| -}
dockerVersion : SelectionSet (Maybe String) Gql.DockerAPI.Object.ImageDetails
dockerVersion =
    Object.selectionForField "(Maybe String)" "dockerVersion" [] (Decode.string |> Decode.nullable)


{-| -}
author : SelectionSet (Maybe String) Gql.DockerAPI.Object.ImageDetails
author =
    Object.selectionForField "(Maybe String)" "author" [] (Decode.string |> Decode.nullable)


{-| -}
config : SelectionSet decodesTo Gql.DockerAPI.Object.ContainerConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ImageDetails
config object_ =
    Object.selectionForCompositeField "config" [] object_ (identity >> Decode.nullable)


{-| -}
architecture : SelectionSet (Maybe String) Gql.DockerAPI.Object.ImageDetails
architecture =
    Object.selectionForField "(Maybe String)" "architecture" [] (Decode.string |> Decode.nullable)


{-| -}
os : SelectionSet (Maybe String) Gql.DockerAPI.Object.ImageDetails
os =
    Object.selectionForField "(Maybe String)" "os" [] (Decode.string |> Decode.nullable)


{-| -}
size : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Long) Gql.DockerAPI.Object.ImageDetails
size =
    Object.selectionForField "(Maybe ScalarCodecs.Long)" "size" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder |> Decode.nullable)


{-| -}
virtualSize : SelectionSet (Maybe String) Gql.DockerAPI.Object.ImageDetails
virtualSize =
    Object.selectionForField "(Maybe String)" "virtualSize" [] (Decode.string |> Decode.nullable)


{-| -}
rootFs : SelectionSet decodesTo Gql.DockerAPI.Object.RootFs -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.ImageDetails
rootFs object_ =
    Object.selectionForCompositeField "rootFs" [] object_ (identity >> Decode.nullable)
