-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.IpamConfig exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
subnet : SelectionSet (Maybe String) Gql.DockerAPI.Object.IpamConfig
subnet =
    Object.selectionForField "(Maybe String)" "subnet" [] (Decode.string |> Decode.nullable)


{-| -}
ipRange : SelectionSet (Maybe String) Gql.DockerAPI.Object.IpamConfig
ipRange =
    Object.selectionForField "(Maybe String)" "ipRange" [] (Decode.string |> Decode.nullable)


{-| -}
gateway : SelectionSet (Maybe String) Gql.DockerAPI.Object.IpamConfig
gateway =
    Object.selectionForField "(Maybe String)" "gateway" [] (Decode.string |> Decode.nullable)
