-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.ManagerStatus exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
leader : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.ManagerStatus
leader =
    Object.selectionForField "(Maybe Bool)" "leader" [] (Decode.bool |> Decode.nullable)


{-| -}
reachability : SelectionSet (Maybe String) Gql.DockerAPI.Object.ManagerStatus
reachability =
    Object.selectionForField "(Maybe String)" "reachability" [] (Decode.string |> Decode.nullable)


{-| -}
addr : SelectionSet (Maybe String) Gql.DockerAPI.Object.ManagerStatus
addr =
    Object.selectionForField "(Maybe String)" "addr" [] (Decode.string |> Decode.nullable)
