-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.Network exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
name : SelectionSet (Maybe String) Gql.DockerAPI.Object.Network
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
id : SelectionSet Gql.DockerAPI.ScalarCodecs.Id Gql.DockerAPI.Object.Network
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
scope : SelectionSet (Maybe String) Gql.DockerAPI.Object.Network
scope =
    Object.selectionForField "(Maybe String)" "scope" [] (Decode.string |> Decode.nullable)


{-| -}
driver : SelectionSet (Maybe String) Gql.DockerAPI.Object.Network
driver =
    Object.selectionForField "(Maybe String)" "driver" [] (Decode.string |> Decode.nullable)


{-| -}
ipam : SelectionSet decodesTo Gql.DockerAPI.Object.Ipam -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.Network
ipam object_ =
    Object.selectionForCompositeField "ipam" [] object_ (identity >> Decode.nullable)


{-| -}
containers : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.Network
containers =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "containers" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
options : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.Network
options =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "options" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
internal : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.Network
internal =
    Object.selectionForField "(Maybe Bool)" "internal" [] (Decode.bool |> Decode.nullable)


{-| -}
enableIPv6 : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.Network
enableIPv6 =
    Object.selectionForField "(Maybe Bool)" "enableIPv6" [] (Decode.bool |> Decode.nullable)


{-| -}
labels : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.Network
labels =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "labels" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
attachable : SelectionSet (Maybe Bool) Gql.DockerAPI.Object.Network
attachable =
    Object.selectionForField "(Maybe Bool)" "attachable" [] (Decode.bool |> Decode.nullable)
