-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.NodeStatus exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
state : SelectionSet (Maybe String) Gql.DockerAPI.Object.NodeStatus
state =
    Object.selectionForField "(Maybe String)" "state" [] (Decode.string |> Decode.nullable)


{-| -}
addr : SelectionSet (Maybe String) Gql.DockerAPI.Object.NodeStatus
addr =
    Object.selectionForField "(Maybe String)" "addr" [] (Decode.string |> Decode.nullable)
