-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.NodeDescription exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
hostname : SelectionSet (Maybe String) Gql.DockerAPI.Object.NodeDescription
hostname =
    Object.selectionForField "(Maybe String)" "hostname" [] (Decode.string |> Decode.nullable)


{-| -}
platform : SelectionSet decodesTo Gql.DockerAPI.Object.Platform -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.NodeDescription
platform object_ =
    Object.selectionForCompositeField "platform" [] object_ (identity >> Decode.nullable)


{-| -}
resources : SelectionSet decodesTo Gql.DockerAPI.Object.Resources -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.NodeDescription
resources object_ =
    Object.selectionForCompositeField "resources" [] object_ (identity >> Decode.nullable)


{-| -}
engine : SelectionSet decodesTo Gql.DockerAPI.Object.EngineConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.NodeDescription
engine object_ =
    Object.selectionForCompositeField "engine" [] object_ (identity >> Decode.nullable)
