-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.NodeInfo exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
id : SelectionSet Gql.DockerAPI.ScalarCodecs.Id Gql.DockerAPI.Object.NodeInfo
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
version : SelectionSet decodesTo Gql.DockerAPI.Object.SwarmVersion -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.NodeInfo
version object_ =
    Object.selectionForCompositeField "version" [] object_ (identity >> Decode.nullable)


{-| -}
createdAt : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Date) Gql.DockerAPI.Object.NodeInfo
createdAt =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "createdAt" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
updatedAt : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Date) Gql.DockerAPI.Object.NodeInfo
updatedAt =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "updatedAt" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
spec : SelectionSet decodesTo Gql.DockerAPI.Object.NodeSpec -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.NodeInfo
spec object_ =
    Object.selectionForCompositeField "spec" [] object_ (identity >> Decode.nullable)


{-| -}
description : SelectionSet decodesTo Gql.DockerAPI.Object.NodeDescription -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.NodeInfo
description object_ =
    Object.selectionForCompositeField "description" [] object_ (identity >> Decode.nullable)


{-| -}
status : SelectionSet decodesTo Gql.DockerAPI.Object.NodeStatus -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.NodeInfo
status object_ =
    Object.selectionForCompositeField "status" [] object_ (identity >> Decode.nullable)


{-| -}
managerStatus : SelectionSet decodesTo Gql.DockerAPI.Object.ManagerStatus -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.NodeInfo
managerStatus object_ =
    Object.selectionForCompositeField "managerStatus" [] object_ (identity >> Decode.nullable)
