-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.Platform exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
architecture : SelectionSet (Maybe String) Gql.DockerAPI.Object.Platform
architecture =
    Object.selectionForField "(Maybe String)" "architecture" [] (Decode.string |> Decode.nullable)


{-| -}
os : SelectionSet (Maybe String) Gql.DockerAPI.Object.Platform
os =
    Object.selectionForField "(Maybe String)" "os" [] (Decode.string |> Decode.nullable)
