-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.PortMapping exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
privatePort : SelectionSet (Maybe Int) Gql.DockerAPI.Object.PortMapping
privatePort =
    Object.selectionForField "(Maybe Int)" "privatePort" [] (Decode.int |> Decode.nullable)


{-| -}
publicPort : SelectionSet (Maybe Int) Gql.DockerAPI.Object.PortMapping
publicPort =
    Object.selectionForField "(Maybe Int)" "publicPort" [] (Decode.int |> Decode.nullable)


{-| -}
type_ : SelectionSet (Maybe String) Gql.DockerAPI.Object.PortMapping
type_ =
    Object.selectionForField "(Maybe String)" "type" [] (Decode.string |> Decode.nullable)


{-| -}
ip : SelectionSet (Maybe String) Gql.DockerAPI.Object.PortMapping
ip =
    Object.selectionForField "(Maybe String)" "ip" [] (Decode.string |> Decode.nullable)
