-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.RaftConfig exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
snapshotInterval : SelectionSet (Maybe Int) Gql.DockerAPI.Object.RaftConfig
snapshotInterval =
    Object.selectionForField "(Maybe Int)" "snapshotInterval" [] (Decode.int |> Decode.nullable)


{-| -}
keepOldSnapshots : SelectionSet (Maybe Int) Gql.DockerAPI.Object.RaftConfig
keepOldSnapshots =
    Object.selectionForField "(Maybe Int)" "keepOldSnapshots" [] (Decode.int |> Decode.nullable)


{-| -}
logEntriesForSlowFollowers : SelectionSet (Maybe Int) Gql.DockerAPI.Object.RaftConfig
logEntriesForSlowFollowers =
    Object.selectionForField "(Maybe Int)" "logEntriesForSlowFollowers" [] (Decode.int |> Decode.nullable)


{-| -}
electionTick : SelectionSet (Maybe Int) Gql.DockerAPI.Object.RaftConfig
electionTick =
    Object.selectionForField "(Maybe Int)" "electionTick" [] (Decode.int |> Decode.nullable)


{-| -}
heartbeatTick : SelectionSet (Maybe Int) Gql.DockerAPI.Object.RaftConfig
heartbeatTick =
    Object.selectionForField "(Maybe Int)" "heartbeatTick" [] (Decode.int |> Decode.nullable)
