-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.RegistryConfig exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
insecureRegistryCidrs : SelectionSet (Maybe (List (Maybe String))) Gql.DockerAPI.Object.RegistryConfig
insecureRegistryCidrs =
    Object.selectionForField "(Maybe (List (Maybe String)))" "insecureRegistryCidrs" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
indexConfigs : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.RegistryConfig
indexConfigs =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "indexConfigs" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)
