-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.SwarmSpec exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
name : SelectionSet (Maybe String) Gql.DockerAPI.Object.SwarmSpec
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
labels : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.SwarmSpec
labels =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "labels" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
orchestration : SelectionSet decodesTo Gql.DockerAPI.Object.OrchestrationConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.SwarmSpec
orchestration object_ =
    Object.selectionForCompositeField "orchestration" [] object_ (identity >> Decode.nullable)


{-| -}
raft : SelectionSet decodesTo Gql.DockerAPI.Object.RaftConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.SwarmSpec
raft object_ =
    Object.selectionForCompositeField "raft" [] object_ (identity >> Decode.nullable)


{-| -}
dispatcher : SelectionSet decodesTo Gql.DockerAPI.Object.DispatcherConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.SwarmSpec
dispatcher object_ =
    Object.selectionForCompositeField "dispatcher" [] object_ (identity >> Decode.nullable)


{-| -}
caConfig : SelectionSet decodesTo Gql.DockerAPI.Object.CaConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.SwarmSpec
caConfig object_ =
    Object.selectionForCompositeField "caConfig" [] object_ (identity >> Decode.nullable)


{-| -}
encryptionConfig : SelectionSet decodesTo Gql.DockerAPI.Object.EncryptionConfig -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.SwarmSpec
encryptionConfig object_ =
    Object.selectionForCompositeField "encryptionConfig" [] object_ (identity >> Decode.nullable)


{-| -}
taskDefaults : SelectionSet decodesTo Gql.DockerAPI.Object.TaskDefaults -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.SwarmSpec
taskDefaults object_ =
    Object.selectionForCompositeField "taskDefaults" [] object_ (identity >> Decode.nullable)
