-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.SwarmCluster exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
id : SelectionSet Gql.DockerAPI.ScalarCodecs.Id Gql.DockerAPI.Object.SwarmCluster
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
version : SelectionSet decodesTo Gql.DockerAPI.Object.SwarmVersion -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.SwarmCluster
version object_ =
    Object.selectionForCompositeField "version" [] object_ (identity >> Decode.nullable)


{-| -}
createdAt : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Date) Gql.DockerAPI.Object.SwarmCluster
createdAt =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "createdAt" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
updatedAt : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.Date) Gql.DockerAPI.Object.SwarmCluster
updatedAt =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "updatedAt" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| -}
swarmSpec : SelectionSet decodesTo Gql.DockerAPI.Object.SwarmSpec -> SelectionSet (Maybe decodesTo) Gql.DockerAPI.Object.SwarmCluster
swarmSpec object_ =
    Object.selectionForCompositeField "swarmSpec" [] object_ (identity >> Decode.nullable)
