-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.SystemVersion exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
apiVersion : SelectionSet String Gql.DockerAPI.Object.SystemVersion
apiVersion =
    Object.selectionForField "String" "apiVersion" [] Decode.string


{-| -}
arch : SelectionSet String Gql.DockerAPI.Object.SystemVersion
arch =
    Object.selectionForField "String" "arch" [] Decode.string


{-| -}
buildTime : SelectionSet String Gql.DockerAPI.Object.SystemVersion
buildTime =
    Object.selectionForField "String" "buildTime" [] Decode.string


{-| -}
gitCommit : SelectionSet String Gql.DockerAPI.Object.SystemVersion
gitCommit =
    Object.selectionForField "String" "gitCommit" [] Decode.string


{-| -}
goVersion : SelectionSet String Gql.DockerAPI.Object.SystemVersion
goVersion =
    Object.selectionForField "String" "goVersion" [] Decode.string


{-| -}
kernelVersion : SelectionSet String Gql.DockerAPI.Object.SystemVersion
kernelVersion =
    Object.selectionForField "String" "kernelVersion" [] Decode.string


{-| -}
os : SelectionSet String Gql.DockerAPI.Object.SystemVersion
os =
    Object.selectionForField "String" "os" [] Decode.string


{-| -}
version : SelectionSet String Gql.DockerAPI.Object.SystemVersion
version =
    Object.selectionForField "String" "version" [] Decode.string
