-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object.Volume exposing (..)

import Gql.DockerAPI.InputObject
import Gql.DockerAPI.Interface
import Gql.DockerAPI.Object
import Gql.DockerAPI.Scalar
import Gql.DockerAPI.ScalarCodecs
import Gql.DockerAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
name : SelectionSet (Maybe String) Gql.DockerAPI.Object.Volume
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
driver : SelectionSet (Maybe String) Gql.DockerAPI.Object.Volume
driver =
    Object.selectionForField "(Maybe String)" "driver" [] (Decode.string |> Decode.nullable)


{-| -}
driverOpts : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.Volume
driverOpts =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "driverOpts" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
labels : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.Volume
labels =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "labels" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)


{-| -}
mountpoint : SelectionSet (Maybe String) Gql.DockerAPI.Object.Volume
mountpoint =
    Object.selectionForField "(Maybe String)" "mountpoint" [] (Decode.string |> Decode.nullable)


{-| -}
scope : SelectionSet (Maybe String) Gql.DockerAPI.Object.Volume
scope =
    Object.selectionForField "(Maybe String)" "scope" [] (Decode.string |> Decode.nullable)


{-| -}
status : SelectionSet (Maybe Gql.DockerAPI.ScalarCodecs.StringAnyMap) Gql.DockerAPI.Object.Volume
status =
    Object.selectionForField "(Maybe ScalarCodecs.StringAnyMap)" "status" [] (Gql.DockerAPI.ScalarCodecs.codecs |> Gql.DockerAPI.Scalar.unwrapCodecs |> .codecStringAnyMap |> .decoder |> Decode.nullable)
