-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.Object exposing (..)


type BlkioDeviceRate
    = BlkioDeviceRate


type BlkioWeightDevice
    = BlkioWeightDevice


type CaConfig
    = CaConfig


type Container
    = Container


type ContainerChange
    = ContainerChange


type ContainerConfig
    = ContainerConfig


type ContainerDetails
    = ContainerDetails


type ContainerMount
    = ContainerMount


type ContainerState
    = ContainerState


type ContainerStats
    = ContainerStats


type CpuStats
    = CpuStats


type CpuUsage
    = CpuUsage


type Device
    = Device


type DispatcherConfig
    = DispatcherConfig


type Driver
    = Driver


type EncryptionConfig
    = EncryptionConfig


type EngineConfig
    = EngineConfig


type EnginePlugin
    = EnginePlugin


type ExternalCa
    = ExternalCa


type Health
    = Health


type HealthLog
    = HealthLog


type Healthcheck
    = Healthcheck


type HostConfig
    = HostConfig


type Image
    = Image


type ImageDetails
    = ImageDetails


type ImageHistory
    = ImageHistory


type ImageSearchResult
    = ImageSearchResult


type Ipam
    = Ipam


type IpamConfig
    = IpamConfig


type JoinTokens
    = JoinTokens


type LogConfig
    = LogConfig


type LxcConfParameter
    = LxcConfParameter


type ManagerStatus
    = ManagerStatus


type MemoryStats
    = MemoryStats


type Network
    = Network


type NetworkSettings
    = NetworkSettings


type NetworkStats
    = NetworkStats


type NetworkingConfig
    = NetworkingConfig


type Node
    = Node


type NodeDescription
    = NodeDescription


type NodeInfo
    = NodeInfo


type NodeSpec
    = NodeSpec


type NodeStatus
    = NodeStatus


type OrchestrationConfig
    = OrchestrationConfig


type Platform
    = Platform


type Plugins
    = Plugins


type PortMapping
    = PortMapping


type RaftConfig
    = RaftConfig


type RegistryConfig
    = RegistryConfig


type RemoteManager
    = RemoteManager


type Resources
    = Resources


type RestartPolicy
    = RestartPolicy


type RootFs
    = RootFs


type Stats
    = Stats


type Swarm
    = Swarm


type SwarmCluster
    = SwarmCluster


type SwarmInfo
    = SwarmInfo


type SwarmNode
    = SwarmNode


type SwarmSpec
    = SwarmSpec


type SwarmVersion
    = SwarmVersion


type System
    = System


type SystemInfo
    = SystemInfo


type SystemVersion
    = SystemVersion


type TaskDefaults
    = TaskDefaults


type ThrottlingData
    = ThrottlingData


type TopResults
    = TopResults


type Ulimit
    = Ulimit


type UnlockKey
    = UnlockKey


type Volume
    = Volume


type VolumeList
    = VolumeList
