-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.DockerAPI.ScalarCodecs exposing (..)

import Gql.DockerAPI.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias BigInteger =
    Gql.DockerAPI.Scalar.BigInteger


type alias Date =
    Gql.DockerAPI.Scalar.Date


type alias Id =
    Gql.DockerAPI.Scalar.Id


type alias Long =
    Gql.DockerAPI.Scalar.Long


type alias StringAnyMap =
    Gql.DockerAPI.Scalar.StringAnyMap


type alias StringSet =
    Gql.DockerAPI.Scalar.StringSet


codecs : Gql.DockerAPI.Scalar.Codecs BigInteger Date Id Long StringAnyMap StringSet
codecs =
    Gql.DockerAPI.Scalar.defineCodecs
        { codecBigInteger = defaultCodecs.codecBigInteger
        , codecDate = defaultCodecs.codecDate
        , codecId = defaultCodecs.codecId
        , codecLong = defaultCodecs.codecLong
        , codecStringAnyMap = defaultCodecs.codecStringAnyMap
        , codecStringSet = defaultCodecs.codecStringSet
        }
